name: Build and Release

on:
  push:
    branches:
      - main
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'

permissions:
    contents: write

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'chore: atualiza tag version do .csproj')"
    runs-on: windows-latest
    env:
      CONFIGURATION: Release
      RUNTIME: win-x64

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Determinar versão do projeto
        id: version
        run: |
          $now = Get-Date
          $version = "1.0.{0:yy}.{0:MMdd}" -f $now
          echo "version=$version" >> $env:GITHUB_OUTPUT

      - name: Atualizar versão no .csproj
        run: |
          $csproj = Get-ChildItem -Path . -Filter *.csproj | Select-Object -First 1
          $versao = "${{ steps.version.outputs.version }}"
          $content = Get-Content $csproj.FullName -Raw

          if ($content -match '<Version>.*?</Version>') {
              $content = $content -replace '<Version>.*?</Version>', "<Version>$versao</Version>"
          } else {
              $content = $content -replace '</PropertyGroup>', "	<Version>$versao</Version>`n</PropertyGroup>"
          }

          $content | Set-Content $csproj.FullName

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull origin main --rebase
          git add $csproj.FullName
          git commit -m "chore: atualiza tag version do .csproj para v${{ steps.version.outputs.version }}"
          git push

      - name: Publicar aplicação
        run: >
          dotnet publish -c $env:CONFIGURATION -r $env:RUNTIME
          --self-contained true /p:PublishSingleFile=true
          -o publish

      - name: Instalar Inno Setup
        run: |
          Write-Host "Baixando InnoSetup por choco..."
          choco install innosetup -y

      - name: Criar instalador com InnoSetup
        run: |
          Write-Host "Baixando InnoSetup..."
          Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe" -OutFile "innosetup.exe"
          Write-Host "Instalando InnoSetup..."
          Start-Process -FilePath "innosetup.exe" -ArgumentList "/VERYSILENT", "/SUPPRESSMSGBOXES", "/NORESTART" -Wait
          Write-Host "InnoSetup instalado com sucesso."
          
          Write-Host "Criando script InnoSetup..."
          $scriptContent = @"
          #define MyAppName "${{ steps.project-info.outputs.project_name }}"
          #define MyAppVersion "${{ steps.project-info.outputs.version }}"

          [Setup]
          AppName={#MyAppName}
          AppVersion={#MyAppVersion}
          AppPublisher=Lucas Coelho Santos
          DefaultDirName={commonpf}\{#MyAppName}
          DefaultGroupName={#MyAppName}
          Compression=lzma2
          SolidCompression=yes
          OutputDir=.
          OutputBaseFilename={#MyAppName}_Setup_{#MyAppVersion}
          WizardStyle=modern

          ; Configurações de idioma (PT-BR)
          [Languages]
          Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"
          
          [Files]
          Source: "publish\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs
          
          [Icons]
          Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppName}.exe"
          Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppName}.exe"
          
          [Run]
          Filename: "{app}\{#MyAppName}.exe"; Description: "Iniciar {#MyAppName}"; Flags: nowait postinstall

          [Code]
          function InitializeSetup(): Boolean;
          var
            ResultCode: Integer;
          begin
            // Verifica se o aplicativo está em execução e tenta fechá-lo
            if Exec('taskkill.exe', '/F /IM {#MyAppName}.exe', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
            begin
              // Aguarda um momento para garantir que o processo foi encerrado
              Sleep(1000);
            end;
            Result := True;
          end;
          "@
          
          Set-Content -Path "setup.iss" -Value $scriptContent
          Write-Host "Script InnoSetup criado com sucesso."
          
          & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' setup.iss

      - name: Criar tag Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -a "v${{ steps.version.outputs.version }}" -m "Versão ${{ steps.version.outputs.version }}"
          git push origin "v${{ steps.version.outputs.version }}"

      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: v${{ steps.version.outputs.version }}
          files: publish/${{ steps.project-info.outputs.project_name }}.exe

      - name: Atualizar version.json no repositório
        run: |
          $json = @{
            version = "${{ steps.version.outputs.version }}"
            url = "https://github.com/${{ github.repository }}/releases/download/v${{ steps.version.outputs.version }}/${{ steps.project-info.outputs.project_name }}.exe"
            directUrl = "https://github.com/${{ github.repository }}/releases/download/v${{ steps.project-info.outputs.version }}/${{ steps.project-info.outputs.project_name }}.exe"
            changelog = "Versão ${{ steps.project-info.outputs.version }} disponibilizada em $(Get-Date -Format 'dd/MM/yyyy')"
          } | ConvertTo-Json -Depth 2
          $json | Out-File -Encoding utf8 version.json

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull origin main --rebase
          git add version.json
          git commit -m "chore: atualiza version.json para v${{ steps.version.outputs.version }}"
          git push